# Generated by Django 5.0.4 on 2026-06-28 09:48

import django.db.models.deletion
import merchant_staff.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants", "0019_restaurant_timestamps"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantStaffMember",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("ADMIN", "Admin"),
                            ("BRANCH_MANAGER", "Branch manager"),
                            ("KITCHEN_STAFF", "Kitchen staff"),
                            ("CASHIER", "Cashier"),
                            ("DISPATCHER", "Dispatcher"),
                            ("CUSTOMER_SUPPORT", "Customer support"),
                            ("FINANCE_STAFF", "Finance staff"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="VIEWER",
                        max_length=32,
                    ),
                ),
                (
                    "membership_status",
                    models.CharField(
                        choices=[
                            ("INVITED", "Invited"),
                            ("PENDING_VERIFICATION", "Pending verification"),
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("REMOVED", "Removed"),
                        ],
                        default="INVITED",
                        max_length=32,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUBMITTED", "Submitted"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                            ("SUSPENDED", "Suspended"),
                            ("MORE_INFO_REQUIRED", "More information required"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                ("verification_rejection_reason", models.TextField(blank=True)),
                (
                    "verification_submitted_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "verification_reviewed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("is_company_wide", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_merchant_staff_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_members",
                        to="restaurants.merchantprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_merchant_staff_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_staff_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verification_reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_merchant_staff_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("merchant__business_name", "user__username", "id"),
            },
        ),
        migrations.CreateModel(
            name="MerchantStaffInvite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("ADMIN", "Admin"),
                            ("BRANCH_MANAGER", "Branch manager"),
                            ("KITCHEN_STAFF", "Kitchen staff"),
                            ("CASHIER", "Cashier"),
                            ("DISPATCHER", "Dispatcher"),
                            ("CUSTOMER_SUPPORT", "Customer support"),
                            ("FINANCE_STAFF", "Finance staff"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="VIEWER",
                        max_length=32,
                    ),
                ),
                ("is_company_wide", models.BooleanField(default=False)),
                (
                    "invite_token",
                    models.CharField(
                        default=merchant_staff.models.merchant_staff_invite_token,
                        max_length=96,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=merchant_staff.models.merchant_staff_invite_expiry
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branches",
                    models.ManyToManyField(
                        blank=True,
                        related_name="staff_invites",
                        to="restaurants.restaurant",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merchant_staff_invites_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_invites",
                        to="restaurants.merchantprofile",
                    ),
                ),
                (
                    "linked_staff_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_invites",
                        to="merchant_staff.merchantstaffmember",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="MerchantStaffBranchAccess",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_access",
                        to="restaurants.restaurant",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_merchant_staff_branch_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_access",
                        to="merchant_staff.merchantstaffmember",
                    ),
                ),
            ],
            options={
                "ordering": ("staff_member", "branch__branch_name", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="merchantstaffmember",
            index=models.Index(
                fields=["merchant", "role", "membership_status"],
                name="merchant_st_merchan_a801fb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="merchantstaffmember",
            index=models.Index(
                fields=["merchant", "verification_status"],
                name="merchant_st_merchan_15c221_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="merchantstaffmember",
            index=models.Index(
                fields=["user", "membership_status"],
                name="merchant_st_user_id_10bdc7_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="merchantstaffmember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("membership_status", "REMOVED"), _negated=True),
                fields=("merchant", "user"),
                name="unique_current_staff_member_per_merchant_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="merchantstaffmember",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("membership_status", "ACTIVE"), _negated=True),
                    ("verification_status", "VERIFIED"),
                    _connector="OR",
                ),
                name="active_staff_requires_verified_identity",
            ),
        ),
        migrations.AddIndex(
            model_name="merchantstaffinvite",
            index=models.Index(
                fields=["merchant", "status"], name="merchant_st_merchan_314f04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="merchantstaffinvite",
            index=models.Index(
                fields=["invite_token"], name="merchant_st_invite__134b61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="merchantstaffinvite",
            index=models.Index(
                fields=["expires_at"], name="merchant_st_expires_6af866_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="merchantstaffbranchaccess",
            index=models.Index(
                fields=["branch", "created_at"], name="merchant_st_branch__8ea2c2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="merchantstaffbranchaccess",
            constraint=models.UniqueConstraint(
                fields=("staff_member", "branch"), name="unique_staff_branch_access"
            ),
        ),
    ]
