# Generated by Django 6.0 on 2026-01-02 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rest_name", models.CharField(max_length=100)),
                ("rest_email", models.EmailField(max_length=254, unique=True)),
                ("rest_contact", models.CharField(max_length=15)),
                ("rest_address", models.TextField()),
                ("rest_city", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_name", models.CharField(max_length=100)),
                ("food_desc", models.TextField(blank=True)),
                ("food_price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "food_categ",
                    models.CharField(
                        choices=[
                            ("Vegetarian", "Vegetarian"),
                            ("Non-Vegetarian", "Non-Vegetarian"),
                            ("Beverages", "Beverages"),
                            ("Desserts", "Desserts"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_items",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
        ),
    ]
