# Generated by Django for T-Food merchant subscription display foundation.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0020_reviewphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='subscription_plan',
            field=models.CharField(
                choices=[
                    ('NOT_CONFIGURED', 'Not configured'),
                    ('TRIAL', 'Trial'),
                    ('MONTHLY', 'Monthly'),
                    ('YEARLY', 'Yearly'),
                ],
                default='NOT_CONFIGURED',
                max_length=20,
            ),
        ),
    ]
