# Generated by Django for T-Food branch delivery partner routing.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0021_merchantprofile_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_mode',
            field=models.CharField(
                choices=[
                    ('T_FOOD_DELIVERY', 'T-Food delivery partners'),
                    ('MERCHANT_DELIVERY', 'Merchant delivery partners'),
                    ('HYBRID', 'Merchant first, then T-Food partners'),
                ],
                default='HYBRID',
                max_length=24,
            ),
        ),
    ]
