from django.urls import path

from .operations_views import (
    OperationsCustomerListView,
    OperationsBranchListView,
    OperationsBranchStatusView,
    OperationsMerchantListView,
    OperationsMerchantRiderListView,
    OperationsMerchantStatusView,
    OperationsNotificationArchiveView,
    OperationsNotificationDismissView,
    OperationsNotificationListView,
    OperationsNotificationReadAllView,
    OperationsNotificationReadView,
    OperationsOrderListView,
    OperationsPartnerListView,
    OperationsPartnerStatusView,
    OperationsPartnerPayoutListView,
    OperationsPartnerPayoutPayView,
    OperationsPaymentProviderConfigDetailView,
    OperationsPaymentProviderConfigListView,
    OperationsRestaurantListView,
    OperationsRevenueView,
    OperationsReviewPhotoDetailView,
    OperationsReviewPhotoListView,
    OperationsStaffListView,
    OperationsMerchantPayoutListView,
    OperationsMerchantPayoutPayView,
    OperationsSummaryView,
    OperationsSupportTicketListView,
    OperationsSupportTicketStatusView,
    OperationsDispatchAssignView,
    OperationsDispatchListView,
    OperationsFulfillmentRequestDetailView,
    OperationsFulfillmentRequestListView,
    OperationsLedgerView,
)
from .verification_views import (
    OperationsDocumentReviewView,
    OperationsMerchantDocumentListView,
    OperationsPartnerDocumentListView,
    OperationsStaffDocumentListView,
    OperationsStaffStatusView,
)
from operations_access.api_views import (
    OperationsAccessAreaScopeView,
    OperationsAccessCityScopeView,
    OperationsAccessMarketScopeView,
    OperationsAccessMeView,
    OperationsAccessStaffDetailView,
    OperationsAccessStaffListCreateView,
)


urlpatterns = [
    path('summary/', OperationsSummaryView.as_view()),
    path('customers/', OperationsCustomerListView.as_view()),
    path('branches/', OperationsBranchListView.as_view()),
    path('branches/<int:branch_id>/status/', OperationsBranchStatusView.as_view()),
    path('restaurants/', OperationsRestaurantListView.as_view()),
    path('orders/', OperationsOrderListView.as_view()),
    path('revenue/', OperationsRevenueView.as_view()),
    path('ledger/', OperationsLedgerView.as_view()),
    path('payment-providers/', OperationsPaymentProviderConfigListView.as_view()),
    path('payment-providers/<int:config_id>/', OperationsPaymentProviderConfigDetailView.as_view()),
    path('notifications/', OperationsNotificationListView.as_view()),
    path('notifications/read-all/', OperationsNotificationReadAllView.as_view()),
    path('notifications/<int:notification_id>/read/', OperationsNotificationReadView.as_view()),
    path('notifications/<int:notification_id>/archive/', OperationsNotificationArchiveView.as_view()),
    path('notifications/<int:notification_id>/dismiss/', OperationsNotificationDismissView.as_view()),
    path('merchants/', OperationsMerchantListView.as_view()),
    path('merchant-riders/', OperationsMerchantRiderListView.as_view()),
    path('merchants/<int:merchant_id>/status/', OperationsMerchantStatusView.as_view()),
    path('merchants/<int:merchant_id>/documents/', OperationsMerchantDocumentListView.as_view()),
    path('partners/', OperationsPartnerListView.as_view()),
    path('partners/<int:partner_id>/status/', OperationsPartnerStatusView.as_view()),
    path('partners/<int:partner_id>/documents/', OperationsPartnerDocumentListView.as_view()),
    path('staff/', OperationsStaffListView.as_view()),
    path('staff/<int:staff_id>/status/', OperationsStaffStatusView.as_view()),
    path('staff/<int:staff_id>/verification/', OperationsStaffStatusView.as_view()),
    path('staff/<int:staff_id>/documents/', OperationsStaffDocumentListView.as_view()),
    path('staff/documents/<int:document_id>/review/', OperationsDocumentReviewView.as_view()),
    path('verification-documents/<int:document_id>/review/', OperationsDocumentReviewView.as_view()),
    path('support/', OperationsSupportTicketListView.as_view()),
    path('support/<int:ticket_id>/status/', OperationsSupportTicketStatusView.as_view()),
    path('review-photos/', OperationsReviewPhotoListView.as_view()),
    path('review-photos/<int:photo_id>/', OperationsReviewPhotoDetailView.as_view()),
    path('dispatch/', OperationsDispatchListView.as_view()),
    path('dispatch/<int:delivery_id>/assign/', OperationsDispatchAssignView.as_view()),
    path('fulfillment-requests/', OperationsFulfillmentRequestListView.as_view()),
    path(
        'fulfillment-requests/<int:fulfillment_request_id>/',
        OperationsFulfillmentRequestDetailView.as_view(),
    ),
    path('payouts/partners/', OperationsPartnerPayoutListView.as_view()),
    path('payouts/partners/<int:delivery_id>/pay/', OperationsPartnerPayoutPayView.as_view()),
    path('payouts/merchants/', OperationsMerchantPayoutListView.as_view()),
    path('payouts/merchants/<int:order_id>/pay/', OperationsMerchantPayoutPayView.as_view()),
    path('access/me/', OperationsAccessMeView.as_view()),
    path('access/staff/', OperationsAccessStaffListCreateView.as_view()),
    path('access/staff/<int:profile_id>/', OperationsAccessStaffDetailView.as_view()),
    path('access/staff/<int:profile_id>/markets/', OperationsAccessMarketScopeView.as_view()),
    path('access/staff/<int:profile_id>/cities/', OperationsAccessCityScopeView.as_view()),
    path('access/staff/<int:profile_id>/areas/', OperationsAccessAreaScopeView.as_view()),
    path(
        'access/staff/<int:profile_id>/markets/<int:object_id>/',
        OperationsAccessMarketScopeView.as_view(),
    ),
    path(
        'access/staff/<int:profile_id>/cities/<int:object_id>/',
        OperationsAccessCityScopeView.as_view(),
    ),
    path(
        'access/staff/<int:profile_id>/areas/<int:object_id>/',
        OperationsAccessAreaScopeView.as_view(),
    ),
]
