# Generated by Django 5.1.3 on 2026-06-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationdeliveryattempt_notificationtemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ORDER', 'Order'), ('PAYMENT', 'Payment'), ('DELIVERY', 'Delivery'), ('MERCHANT', 'Merchant'), ('STAFF', 'Staff'), ('RIDER', 'Rider'), ('SUPPORT', 'Support'), ('VERIFICATION', 'Verification'), ('DISPATCH', 'Dispatch'), ('INTELLIGENCE', 'Intelligence'), ('SYSTEM', 'System')], max_length=30)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-app'), ('REALTIME', 'Realtime'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push'), ('WHATSAPP', 'WhatsApp'), ('TELEGRAM', 'Telegram')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('category', 'channel'),
            },
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['user', 'category', 'channel'], name='notificatio_user_id_90fe9e_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['channel', 'enabled'], name='notificatio_channel_f15f2c_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationpreference',
            constraint=models.UniqueConstraint(fields=('user', 'category', 'channel'), name='unique_notification_preference_user_category_channel'),
        ),
    ]
