# Generated by Django 5.1.3 on 2026-06-30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notificationpreference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('WEB', 'Web'), ('ANDROID', 'Android'), ('IOS', 'iOS')], max_length=20)),
                ('device_identifier', models.CharField(max_length=160)),
                ('push_token', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='notificationdevice',
            index=models.Index(fields=['user', 'device_type', 'is_active'], name='notificatio_user_id_2dbb0d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdevice',
            index=models.Index(fields=['device_identifier'], name='notificatio_device__4fdafb_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationdevice',
            constraint=models.UniqueConstraint(fields=('user', 'device_identifier'), name='unique_notification_device_user_identifier'),
        ),
    ]
