# Generated by Django 5.2.6 on 2026-01-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0002_alter_delivery_id_alter_deliverypartner_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="current_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="current_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
