# Generated by Django 5.0.4 on 2026-06-25 13:19

import delivery.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0010_delivery_gis_points"),
        ("restaurants", "0014_restaurant_pickup_point"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantRider",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INVITED", "Invited"),
                            ("PENDING_APPROVAL", "Pending approval"),
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("REMOVED", "Removed"),
                        ],
                        default="PENDING_APPROVAL",
                        max_length=24,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_merchant_riders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "home_restaurant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merchant_riders",
                        to="restaurants.restaurant",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invited_merchant_riders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_riders",
                        to="restaurants.merchantprofile",
                    ),
                ),
                (
                    "partner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_rider_link",
                        to="delivery.deliverypartner",
                    ),
                ),
            ],
            options={
                "ordering": ("merchant__business_name", "partner__partner_name", "id"),
                "indexes": [
                    models.Index(
                        fields=["merchant", "status"],
                        name="delivery_me_merchan_bae4a6_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="delivery_me_status_5e07d3_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MerchantRiderInvite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("transport_type", models.CharField(blank=True, max_length=100)),
                (
                    "invite_token",
                    models.CharField(
                        default=delivery.models.merchant_rider_invite_token,
                        max_length=96,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=delivery.models.merchant_rider_invite_expiry
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merchant_rider_invites_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merchant_rider_invites",
                        to="delivery.deliverypartner",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rider_invites",
                        to="restaurants.merchantprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["merchant", "status"],
                        name="delivery_me_merchan_9fe58a_idx",
                    ),
                    models.Index(
                        fields=["invite_token"], name="delivery_me_invite__ffa362_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="delivery_me_expires_c86362_idx"
                    ),
                ],
            },
        ),
    ]
