# Generated by Django 5.0.4 on 2026-06-25 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0011_merchantrider_merchantriderinvite"),
        ("restaurants", "0014_restaurant_pickup_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantriderinvite",
            name="home_restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merchant_rider_invites",
                to="restaurants.restaurant",
            ),
        ),
    ]
