# Generated by Django 5.0.4 on 2026-06-28 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("markets", "0005_commercecity_commercearea_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationsStaffProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("GLOBAL_ADMIN", "Global admin"),
                            ("COUNTRY_ADMIN", "Country admin"),
                            ("CITY_ADMIN", "City admin"),
                            ("AREA_ADMIN", "Area admin"),
                            ("OPERATIONS_STAFF", "Operations staff"),
                            ("SUPPORT_STAFF", "Support staff"),
                            ("FINANCE_STAFF", "Finance staff"),
                            ("VERIFICATION_REVIEWER", "Verification reviewer"),
                            ("DISPATCH_OPERATOR", "Dispatch operator"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="OPERATIONS_STAFF",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("permissions", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_operations_staff_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_operations_staff_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations_staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("user__username", "id"),
            },
        ),
        migrations.CreateModel(
            name="OperationsStaffMarketAccess",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_operations_market_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations_staff_access",
                        to="markets.market",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_access",
                        to="operations_access.operationsstaffprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("profile", "market__name", "id"),
            },
        ),
        migrations.CreateModel(
            name="OperationsStaffCityAccess",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations_staff_access",
                        to="markets.commercecity",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_operations_city_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="city_access",
                        to="operations_access.operationsstaffprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("profile", "city__name", "id"),
            },
        ),
        migrations.CreateModel(
            name="OperationsStaffAreaAccess",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations_staff_access",
                        to="markets.commercearea",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_operations_area_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="area_access",
                        to="operations_access.operationsstaffprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("profile", "area__name", "id"),
            },
        ),
        migrations.CreateModel(
            name="OperationsAccessAudit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=80)),
                ("target_type", models.CharField(blank=True, max_length=80)),
                ("target_id", models.CharField(blank=True, max_length=80)),
                ("scope_type", models.CharField(blank=True, max_length=40)),
                ("scope_id", models.CharField(blank=True, max_length=80)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operations_access_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["actor", "created_at"],
                        name="operations__actor_i_a8fc31_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="operations__action_3aeea4_idx",
                    ),
                    models.Index(
                        fields=["scope_type", "scope_id"],
                        name="operations__scope_t_5148dd_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="operationsstaffprofile",
            index=models.Index(
                fields=["role", "status"], name="operations__role_58ba40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="operationsstaffprofile",
            index=models.Index(
                fields=["status", "created_at"], name="operations__status_efca3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="operationsstaffmarketaccess",
            index=models.Index(
                fields=["market", "created_at"], name="operations__market__c4684c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="operationsstaffmarketaccess",
            constraint=models.UniqueConstraint(
                fields=("profile", "market"),
                name="unique_operations_profile_market_access",
            ),
        ),
        migrations.AddIndex(
            model_name="operationsstaffcityaccess",
            index=models.Index(
                fields=["city", "created_at"], name="operations__city_id_6d219f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="operationsstaffcityaccess",
            constraint=models.UniqueConstraint(
                fields=("profile", "city"), name="unique_operations_profile_city_access"
            ),
        ),
        migrations.AddIndex(
            model_name="operationsstaffareaaccess",
            index=models.Index(
                fields=["area", "created_at"], name="operations__area_id_c7a92b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="operationsstaffareaaccess",
            constraint=models.UniqueConstraint(
                fields=("profile", "area"), name="unique_operations_profile_area_access"
            ),
        ),
    ]
