# Generated by Django 5.0.4 on 2026-06-28 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0005_commercecity_commercearea_and_more"),
        ("verifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("AADHAAR", "Aadhaar"),
                    ("BUSINESS_DOCUMENT", "Business document"),
                    ("DRIVING_LICENSE", "Driving license"),
                    ("NATIONAL_ID", "National ID"),
                    ("OTHER_GOVERNMENT_ID", "Other government ID"),
                    ("OWNER_PROFILE_PHOTO", "Owner profile photo"),
                    ("PARTNER_PROFILE_PHOTO", "Partner profile photo"),
                    ("PASSPORT", "Passport"),
                    ("RESTAURANT_PHOTO", "Restaurant photo"),
                    ("VEHICLE_DOCUMENT", "Vehicle document"),
                    ("VOTER_CARD", "Voter card"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="subject_type",
            field=models.CharField(
                choices=[
                    ("MERCHANT", "Merchant"),
                    ("PARTNER", "Delivery partner"),
                    ("MERCHANT_STAFF", "Merchant staff"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="VerificationDocumentRequirement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(
                        choices=[
                            ("MERCHANT", "Merchant"),
                            ("PARTNER", "Delivery partner"),
                            ("MERCHANT_STAFF", "Merchant staff"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("AADHAAR", "Aadhaar"),
                            ("BUSINESS_DOCUMENT", "Business document"),
                            ("DRIVING_LICENSE", "Driving license"),
                            ("NATIONAL_ID", "National ID"),
                            ("OTHER_GOVERNMENT_ID", "Other government ID"),
                            ("OWNER_PROFILE_PHOTO", "Owner profile photo"),
                            ("PARTNER_PROFILE_PHOTO", "Partner profile photo"),
                            ("PASSPORT", "Passport"),
                            ("RESTAURANT_PHOTO", "Restaurant photo"),
                            ("VEHICLE_DOCUMENT", "Vehicle document"),
                            ("VOTER_CARD", "Voter card"),
                        ],
                        max_length=40,
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("display_name", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "market",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_document_requirements",
                        to="markets.market",
                    ),
                ),
            ],
            options={
                "ordering": ("market__name", "subject_type", "display_name"),
                "indexes": [
                    models.Index(
                        fields=["market", "subject_type", "is_active"],
                        name="verificatio_market__36ceb7_idx",
                    ),
                    models.Index(
                        fields=["subject_type", "is_required", "is_active"],
                        name="verificatio_subject_0657a9_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="verificationdocumentrequirement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("market__isnull", False)),
                fields=("market", "subject_type", "document_type"),
                name="unique_verification_requirement_per_market_subject_doc",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationdocumentrequirement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("market__isnull", True)),
                fields=("subject_type", "document_type"),
                name="unique_global_verification_requirement_subject_doc",
            ),
        ),
    ]
