SUBJECT_MERCHANT = 'MERCHANT'
SUBJECT_PARTNER = 'PARTNER'
SUBJECT_MERCHANT_STAFF = 'MERCHANT_STAFF'

STATUS_PENDING = 'PENDING'
STATUS_APPROVED = 'APPROVED'
STATUS_REJECTED = 'REJECTED'

VERIFICATION_PENDING = 'PENDING'
VERIFICATION_SUBMITTED = 'SUBMITTED'
VERIFICATION_APPROVED = 'APPROVED'
VERIFICATION_REJECTED = 'REJECTED'
VERIFICATION_SUSPENDED = 'SUSPENDED'

DOCUMENT_STATUS_CHOICES = [
    (STATUS_PENDING, 'Pending review'),
    (STATUS_APPROVED, 'Approved'),
    (STATUS_REJECTED, 'Rejected'),
]

VERIFICATION_STATUS_CHOICES = [
    (VERIFICATION_PENDING, 'Pending documents'),
    (VERIFICATION_SUBMITTED, 'Submitted for review'),
    (VERIFICATION_APPROVED, 'Approved'),
    (VERIFICATION_REJECTED, 'Rejected'),
    (VERIFICATION_SUSPENDED, 'Suspended'),
]

MERCHANT_DOCUMENT_TYPES = [
    ('OWNER_PROFILE_PHOTO', 'Owner profile photo'),
    ('NATIONAL_ID', 'National ID'),
    ('PASSPORT', 'Passport'),
    ('VOTER_CARD', 'Voter card'),
    ('BUSINESS_DOCUMENT', 'Business document'),
    ('RESTAURANT_PHOTO', 'Restaurant photo'),
]

PARTNER_DOCUMENT_TYPES = [
    ('PARTNER_PROFILE_PHOTO', 'Partner profile photo'),
    ('NATIONAL_ID', 'National ID'),
    ('PASSPORT', 'Passport'),
    ('DRIVING_LICENSE', 'Driving license'),
    ('VEHICLE_DOCUMENT', 'Vehicle document'),
]

STAFF_DOCUMENT_TYPES = [
    ('NATIONAL_ID', 'National ID'),
    ('PASSPORT', 'Passport'),
    ('VOTER_CARD', 'Voter card'),
    ('DRIVING_LICENSE', 'Driving license'),
    ('AADHAAR', 'Aadhaar'),
    ('OTHER_GOVERNMENT_ID', 'Other government ID'),
]

ALL_DOCUMENT_TYPES = sorted(
    set(MERCHANT_DOCUMENT_TYPES + PARTNER_DOCUMENT_TYPES + STAFF_DOCUMENT_TYPES)
)
MERCHANT_DOCUMENT_VALUES = {value for value, _ in MERCHANT_DOCUMENT_TYPES}
PARTNER_DOCUMENT_VALUES = {value for value, _ in PARTNER_DOCUMENT_TYPES}
STAFF_DOCUMENT_VALUES = {value for value, _ in STAFF_DOCUMENT_TYPES}

MERCHANT_IDENTITY_DOCUMENTS = {'NATIONAL_ID', 'PASSPORT', 'VOTER_CARD'}
PARTNER_IDENTITY_DOCUMENTS = {'NATIONAL_ID', 'PASSPORT', 'DRIVING_LICENSE'}
STAFF_IDENTITY_DOCUMENTS = {
    'NATIONAL_ID',
    'PASSPORT',
    'VOTER_CARD',
    'DRIVING_LICENSE',
    'AADHAAR',
    'OTHER_GOVERNMENT_ID',
}
